### ISSUE TITLE
plugin is not showing in filters

### ISSUE THREAD

**Issue by Anthomy93** [gxalpha/obs-mac-backgroundremoval#4]
For some reason the background removal filter is not appearing in my abs studio filters.

I have installed it multiple times and in ~/Library/Application support contains the plugin folder inside ops studio folder.

can somebody help me please?

current log file:

12:14:57.137: [macOS] Permission for audio device access granted.
12:14:57.147: [macOS] Permission for video device access granted.
12:14:57.153: [macOS] Permission for accessibility denied.
12:14:57.153: [macOS] Permission for screen capture denied.
12:14:57.153: CPU Name: Intel(R) Core(TM) i5-3470S CPU @ 2.90GHz
12:14:57.153: CPU Speed: 2900MHz
12:14:57.153: Physical Cores: 4, Logical Cores: 4
12:14:57.153: Physical Memory: 32768MB Total
12:14:57.153: OS Name: macOS
12:14:57.153: OS Version: Version 10.15.7 (Build 19H2026)
12:14:57.153: Rosetta translation used: false
12:14:57.153: Kernel Version: 19.6.0
12:14:57.154: hotkeys-cocoa: Using layout 'com.apple.keylayout.British'
12:14:57.154: Current Date/Time: 2024-10-09, 12:14:57
12:14:57.154: Browser Hardware Acceleration: true
12:14:57.154: Qt Version: 6.4.1 (runtime), 6.4.1 (compiled)
12:14:57.154: Portable mode: false
12:14:57.365: OBS 29.0.2 (mac)
12:14:57.365: ---------------------------------
12:14:57.367: ---------------------------------
12:14:57.367: audio settings reset:
12:14:57.367: 	samples per sec: 48000
12:14:57.367: 	speakers:        2
12:14:57.367: 	max buffering:   960 milliseconds
12:14:57.367: 	buffering type:  dynamically increasing
12:14:57.368: ---------------------------------
12:14:57.368: Initializing OpenGL...
12:14:57.434: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce GTX 660M OpenGL Engine
12:14:57.434: OpenGL loaded successfully, version 4.1 NVIDIA-14.0.32 355.11.11.10.10.143, shading language 4.10
12:14:57.857: ---------------------------------
12:14:57.857: video settings reset:
12:14:57.857: 	base resolution:   1920x1080
12:14:57.857: 	output resolution: 1920x1080
12:14:57.857: 	downscale filter:  Bicubic
12:14:57.857: 	fps:               30/1
12:14:57.857: 	format:            NV12
12:14:57.857: 	YUV mode:          Rec. 709/Partial
12:14:57.857: NV12 texture support not available
12:14:57.858: P010 texture support not available
12:14:57.858: Audio monitoring device:
12:14:57.858: 	name: Default
12:14:57.858: 	id: default
12:14:57.858: ---------------------------------
12:14:57.865: Failed to load 'en-GB' text for module: 'aja-output-ui'
12:14:57.865: No AJA devices found, skipping loading AJA UI plugin
12:14:57.865: Failed to initialize module 'aja-output-ui'
12:14:57.871: Failed to load 'en-GB' text for module: 'aja'
12:14:57.871: No AJA devices found, skipping loading AJA plugin
12:14:57.871: Failed to initialize module 'aja'
12:14:57.872: Failed to load 'en-GB' text for module: 'coreaudio-encoder'
12:14:57.873: Failed to load 'en-US' text for module: 'decklink-captions'
12:14:57.874: Failed to load 'en-US' text for module: 'decklink-output-ui'
12:14:57.875: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
12:14:57.875: Failed to initialize module 'decklink'
12:14:57.878: Failed to load 'en-GB' text for module: 'frontend-tools'
12:14:58.148: Failed to load 'en-GB' text for module: 'mac-capture'
12:14:58.149: Failed to load 'en-GB' text for module: 'mac-videotoolbox'
12:14:58.237: [VideoToolbox encoder]: Adding VideoToolbox encoders
12:14:58.238: Failed to load 'en-GB' text for module: 'mac-virtualcam'
12:14:58.280: [obs-browser]: Version 2.19.0
12:14:58.280: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.61.23+g2fe5a76+chromium-103.0.5060.134 (compiled)
12:14:58.286: Failed to load 'en-GB' text for module: 'obs-vst'
12:14:58.300: Failed to load 'en-GB' text for module: 'obs-websocket'
12:14:58.300: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.1.0 | RPC Version: 1)
12:14:58.300: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.4.1 | Qt version (run-time): 6.4.1
12:14:58.300: [obs-websocket] [obs_module_load] Linked ASIO Version: 101201
12:14:58.308: [obs-websocket] [obs_module_load] Module loaded.
12:14:58.308: Failed to load 'en-GB' text for module: 'obs-x264'
12:14:58.309: Failed to load 'en-GB' text for module: 'rtmp-services'
12:14:58.312: os_dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib->/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib): dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib, 257): image not found
12:14:58.312: 
12:14:58.312: [vlc-video]: Couldn't find VLC installation, VLC video source disabled
12:14:58.316: os_dlopen(/Users/tomnguyen/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval->/Users/tomnguyen/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval): dlopen(/Users/tomnguyen/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval, 257): Library not loaded: @rpath/obs-frontend-api.dylib
12:14:58.316:   Referenced from: /Users/tomnguyen/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval
12:14:58.316:   Reason: image not found
12:14:58.316: 
12:14:58.316: Module '/Users/tomnguyen/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval' not loaded
12:14:58.374: os_dlopen(/Users/tomnguyen/Library/Application Support/obs-studio/plugins/obs-mac-backgroundremoval.plugin/Contents/MacOS/obs-mac-backgroundremoval->/Users/tomnguyen/Library/Application Support/obs-studio/plugins/obs-mac-backgroundremoval.plugin/Contents/MacOS/obs-mac-backgroundremoval): dlopen(/Users/tomnguyen/Library/Application Support/obs-studio/plugins/obs-mac-backgroundremoval.plugin/Contents/MacOS/obs-mac-backgroundremoval, 257): Symbol not found: _OBJC_CLASS_$_VNGeneratePersonSegmentationRequest
12:14:58.374:   Referenced from: /Users/tomnguyen/Library/Application Support/obs-studio/plugins/obs-mac-backgroundremoval.plugin/Contents/MacOS/obs-mac-backgroundremoval (which was built for Mac OS X 12.0)
12:14:58.374:   Expected in: /System/Library/Frameworks/Vision.framework/Versions/A/Vision
12:14:58.374: 
12:14:58.374: 
12:14:58.374: Module '/Users/tomnguyen/Library/Application Support/obs-studio/plugins/obs-mac-backgroundremoval.plugin/Contents/MacOS/obs-mac-backgroundremoval' not loaded
12:14:58.375: ---------------------------------
12:14:58.375:   Loaded Modules:
12:14:58.375:     vlc-video
12:14:58.375:     text-freetype2
12:14:58.375:     rtmp-services
12:14:58.375:     obs-x264
12:14:58.375:     obs-websocket
12:14:58.375:     obs-vst
12:14:58.375:     obs-transitions
12:14:58.375:     obs-outputs
12:14:58.375:     obs-filters
12:14:58.375:     obs-ffmpeg
12:14:58.375:     obs-browser
12:14:58.375:     mac-virtualcam
12:14:58.375:     mac-videotoolbox
12:14:58.375:     mac-syphon
12:14:58.375:     mac-capture
12:14:58.375:     mac-avcapture
12:14:58.375:     image-source
12:14:58.375:     frontend-tools
12:14:58.375:     decklink-output-ui
12:14:58.375:     decklink-captions
12:14:58.375:     coreaudio-encoder
12:14:58.375: ---------------------------------
12:14:58.375: ==== Startup complete ===============================================
12:14:58.435: All scene data cleared
12:14:58.435: ------------------------------------------------
12:14:58.478: coreaudio: Device 'Built-in Microphone' [44100 Hz] initialized
12:14:58.479: [Loaded global audio device]: 'Mic/Aux'
12:14:58.497: Webcam: Selected device 'FaceTime HD Camera (Built-in)'
12:14:58.500: Webcam: Using preset High
12:14:59.032: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: Mic/Aux)
12:14:59.032: 
12:14:59.034: Switched to scene 'Poker Stream'
12:14:59.034: ------------------------------------------------
12:14:59.034: Loaded scenes:
12:14:59.034: - scene 'Poker Stream':
12:14:59.034:     - source: 'Webcam' (av_capture_input_v2)
12:14:59.034:     - source: 'Poker table' (window_capture)
12:14:59.034:     - source: 'Stream Chat' (window_capture)
12:14:59.034: ------------------------------------------------

**Comment by sebastian-s-beckmann** [comment]
As noted in the README file, macOS 12 is required for this plugin.
